const siteUrl = (process.env.SITE_URL || "https://xinchao-golf.vercel.app").trim().replace(/\/+$/, "");

if (!/^https:\/\/[a-z0-9.-]+(?::\d+)?$/i.test(siteUrl)) {
  throw new Error("SITE_URL은 경로와 마지막 슬래시가 없는 https 주소여야 합니다.");
}

export const site = {
  name: "신짜오골프",
  englishName: "XIN CHAO GOLF",
  siteUrl,
  kakaoUrl: "https://pf.kakao.com/_FXwxkG/chat",
  lastUpdated: "2026-07-17",
  description: "호치민을 중심으로 베트남 골프장, 차량, 아파트와 풀빌라 상담을 연결하는 한국어 골프 전문 안내 사이트",
};

export const courses = [
  {
    slug: "thu-duc-country-club",
    legacy: "golf-detail_hcm_1.html",
    name: "투득 컨트리클럽",
    englishName: "Vietnam Golf & Country Club",
    shortName: "투득CC",
    region: "호치민",
    location: "호치민 투득 지역",
    holes: "36홀",
    access: "호치민 도심에서 이동하기 편한 편",
    image: "course-thu-duc.webp",
    summary: "오랜 운영 역사와 2개의 18홀 코스를 갖춘 호치민 대표 골프장입니다.",
    points: ["36홀 규모", "도심 접근성", "첫 호치민 골프여행에 적합"],
  },
  {
    slug: "tan-son-nhat-golf-course",
    legacy: "golf-detail_hcm_2.html",
    name: "탄손넛 골프코스",
    englishName: "Tan Son Nhat Golf Course",
    shortName: "탄손넛CC",
    region: "호치민",
    location: "떤선녓 공항 인근",
    holes: "36홀",
    access: "공항과 1군에서 접근하기 편리",
    image: "course-tan-son-nhat.webp",
    summary: "공항과 도심 접근성이 좋아 짧은 일정이나 야간 라운드를 상담하기 좋은 골프장입니다.",
    points: ["공항 인접", "36홀 규모", "짧은 일정에 유리"],
  },
  {
    slug: "twin-doves-golf-club",
    legacy: "golf-detail_hcm_3.html",
    name: "트윈도브 골프클럽",
    englishName: "Twin Doves Golf Club",
    shortName: "트윈도브CC",
    region: "호치민 근교",
    location: "빈즈엉",
    holes: "27홀",
    access: "호치민에서 당일 이동 가능",
    image: "course-twin-doves.webp",
    summary: "정돈된 코스와 클럽하우스로 비즈니스 라운드 문의가 많은 멤버십 골프장입니다.",
    points: ["27홀 구성", "관리 상태", "비즈니스 라운드"],
  },
  {
    slug: "leman-golf-club",
    legacy: "golf-detail_hcm_4.html",
    name: "레만 골프클럽",
    englishName: "Leman Golf Club",
    shortName: "레만CC",
    region: "호치민 근교",
    location: "꾸찌",
    holes: "상담 시 확인",
    access: "호치민 북서부 이동 일정에 적합",
    image: "course-leman.webp",
    summary: "꾸찌 방면 일정과 함께 검토할 수 있는 호치민 근교 골프장입니다.",
    points: ["꾸찌 지역", "근교 라운드", "차량 동선 상담"],
  },
  {
    slug: "vung-tau-paradise-golf",
    legacy: "golf-detail_hcm_5.html",
    name: "붕따우 파라다이스 골프클럽",
    englishName: "Vung Tau Paradise Golf Club",
    shortName: "붕따우 파라다이스CC",
    region: "붕따우",
    location: "붕따우 해안",
    holes: "27홀",
    access: "붕따우 숙박 일정과 함께 추천",
    image: "course-vung-tau-paradise.webp",
    summary: "바닷바람과 해안 경관을 함께 즐길 수 있는 붕따우의 대표 골프장입니다.",
    points: ["해안 코스", "27홀 규모", "붕따우 숙박 연계"],
  },
  {
    slug: "the-bluffs-grand-ho-tram",
    legacy: "golf-detail_hcm_6.html",
    name: "더 블러프스 그랜드 호트람",
    englishName: "The Bluffs Grand Ho Tram",
    shortName: "더 블러프스 호트람",
    region: "호트람",
    location: "바리아붕따우 호트람",
    holes: "18홀",
    access: "호트람 숙박 일정과 함께 추천",
    image: "course-the-bluffs.webp",
    summary: "해안 지형과 바람을 활용한 코스로 프리미엄 라운드 문의가 많은 골프장입니다.",
    points: ["해안 링크스 스타일", "18홀", "호트람 숙박 연계"],
  },
  {
    slug: "taekwang-jeongsan-country-club",
    legacy: "golf-detail_dongnai_1.html",
    name: "태광정산 컨트리클럽",
    englishName: "Taekwang Jeongsan Country Club",
    shortName: "태광정산CC",
    region: "동나이",
    location: "동나이강 섬 지역",
    holes: "18홀",
    access: "선착장 이동을 포함해 차량 동선 확인 필요",
    image: "course-taekwang.webp",
    summary: "강과 섬 지형을 활용한 독특한 이동 경험이 특징인 호치민 근교 골프장입니다.",
    points: ["섬 지역 코스", "18홀", "이동 동선 사전 확인"],
  },
  {
    slug: "long-thanh-golf-club",
    legacy: "golf-detail_dongnai_2.html",
    name: "롱탄 골프클럽",
    englishName: "Long Thanh Golf Club",
    shortName: "롱탄CC",
    region: "동나이",
    location: "동나이 롱탄",
    holes: "36홀",
    access: "호치민에서 당일 이동하기 좋은 편",
    image: "course-long-thanh.webp",
    summary: "힐 코스와 레이크 코스를 갖춰 호치민 골프여행에서 자주 문의되는 골프장입니다.",
    points: ["36홀 규모", "다양한 코스", "호치민 인기 문의"],
  },
  {
    slug: "song-be-golf-resort",
    legacy: "golf-detail_dongnai_3.html",
    name: "송베 골프 리조트",
    englishName: "Song Be Golf Resort",
    shortName: "송베CC",
    region: "빈즈엉",
    location: "빈즈엉",
    holes: "27홀",
    access: "호치민 북부 일정에 적합",
    image: "course-song-be.webp",
    summary: "서로 다른 성격의 3개 9홀 코스로 구성된 호치민 근교 골프장입니다.",
    points: ["27홀 구성", "다양한 난이도", "빈즈엉 일정"],
  },
  {
    slug: "dong-nai-golf-resort",
    legacy: "golf-detail_dongnai_4.html",
    name: "동나이 골프 리조트",
    englishName: "Dong Nai Golf Resort",
    shortName: "동나이CC",
    region: "동나이",
    location: "동나이 짱봄",
    holes: "27홀",
    access: "이동시간을 고려한 단독 일정 추천",
    image: "course-dong-nai.webp",
    summary: "호수와 숲을 활용한 자연형 코스로 여유로운 근교 라운드를 원하는 고객에게 적합합니다.",
    points: ["27홀 규모", "자연형 코스", "근교 단독 일정"],
  },
  {
    slug: "harmony-golf-park",
    legacy: "golf-detail_dongnai_5.html",
    name: "하모니 골프파크",
    englishName: "Harmony Golf Park",
    shortName: "하모니CC",
    region: "빈즈엉",
    location: "빈즈엉",
    holes: "18홀",
    access: "호치민에서 당일 이동 가능",
    image: "course-harmony.webp",
    summary: "현대적인 시설과 전략적인 코스 구성으로 호치민 근교 라운드에 검토할 수 있습니다.",
    points: ["18홀", "현대적인 시설", "빈즈엉 동선"],
  },
  {
    slug: "west-lakes-golf-villas",
    legacy: "golf-detail_hcm_7.html",
    name: "웨스트레이크 골프 앤 빌라스",
    englishName: "West Lakes Golf & Villas",
    shortName: "웨스트레이크CC",
    region: "호치민 근교",
    location: "롱안·호치민 서부 방면",
    holes: "예약 시 코스 확인",
    access: "호치민 서부 이동시간과 교통상황을 함께 확인",
    image: "hero-golf.webp",
    summary: "호치민 서부 롱안 방면에서 검토할 수 있는 골프장으로, 일정과 티오프에 맞춘 차량 상담이 필요합니다.",
    points: ["호치민 서부 동선", "롱안 일정 연계", "티오프·차량 사전 확인"],
  },
];

export const regions = [
  { name: "호치민", emphasis: "핵심 지역", text: "도심·동나이·빈즈엉·붕따우까지 일정과 이동 동선을 함께 상담합니다." },
  { name: "하노이", emphasis: "상담 가능", text: "하노이 체류 일정과 이동시간에 맞춰 골프장 조합을 안내합니다." },
  { name: "다낭", emphasis: "상담 가능", text: "다낭·호이안 골프 일정과 숙소·차량을 함께 상담합니다." },
  { name: "나트랑", emphasis: "상담 가능", text: "나트랑 리조트 일정에 맞는 골프장과 차량을 안내합니다." },
  { name: "푸꾸옥", emphasis: "상담 가능", text: "푸꾸옥 체류 기간과 항공 일정에 맞춰 상담합니다." },
];

export const services = [
  {
    slug: "apartment",
    name: "아파트",
    image: "service-apartment.webp",
    text: "골프 인원과 숙박 기간에 맞는 호치민 아파트를 상담합니다.",
  },
  {
    slug: "villa",
    name: "풀빌라",
    image: "service-villa.webp",
    text: "단체 골프여행에 필요한 객실 수와 차량 동선을 함께 검토합니다.",
  },
  {
    slug: "vehicle",
    name: "골프 차량",
    image: "service-vehicle.webp",
    text: "공항 픽업부터 골프장 왕복, 일정 종료까지 필요한 차량을 상담합니다.",
  },
];

export const apartments = [
  { slug: "vinhomes-central-park", legacy: "apartment-detail_1.html", name: "빈홈 센트럴 파크", englishName: "Vinhomes Central Park", area: "빈탄군", image: "stay-vinhomes.webp", text: "1군과 가까운 대형 주거단지로 골프 일정 전후 도심 이동을 함께 검토하기 좋습니다." },
  { slug: "lumiere-riverside", legacy: "apartment-detail_2.html", name: "루미에르 리버사이드", englishName: "Lumiere Riverside", area: "투득시", image: "stay-lumiere.webp", text: "호치민 동부와 투득 방면 골프장 이동을 고려할 때 상담할 수 있는 아파트입니다." },
  { slug: "metropole-thu-thiem", legacy: "apartment-detail_3.html", name: "메트로폴 투티엠", englishName: "Metropole Thu Thiem", area: "투티엠", image: "stay-metropole.webp", text: "1군 접근성과 투티엠 신도시 환경을 함께 원하는 일정에 검토할 수 있습니다." },
  { slug: "sunrise-city", legacy: "apartment-detail_4.html", name: "선라이즈 시티", englishName: "Sunrise City", area: "7군", image: "stay-sunrise.webp", text: "7군 체류와 남부 방면 이동을 고려하는 고객에게 안내할 수 있는 아파트입니다." },
];

export const villas = [
  { slug: "villa-9a", legacy: "villa-detail_hcm_1.html", name: "Villa 9A", spec: "침실 4개 · 욕실 4개", image: "villa-9a.webp" },
  { slug: "villa-109", legacy: "villa-detail_hcm_2.html", name: "Villa 109", spec: "침실 5개 · 욕실 5개", image: "villa-109.webp" },
  { slug: "villa-1f", legacy: "villa-detail_hcm_3.html", name: "Villa 1F", spec: "침실 4개 · 욕실 4개", image: "villa-1f.webp" },
  { slug: "villa-b7", legacy: "villa-detail_hcm_4.html", name: "Villa B7", spec: "침실 6개 · 욕실 7개", image: "villa-b7.webp" },
  { slug: "villa-cadina", legacy: "villa-detail_hcm_5.html", name: "Villa Cadina", spec: "침실 6개 · 욕실 8개", image: "villa-cadina.webp" },
  { slug: "villa-cadina-1", legacy: "villa-detail_hcm_6.html", name: "Villa Cadina 1", spec: "침실 4개 · 욕실 4개", image: "villa-cadina-1.webp" },
  { slug: "villa-cadina-2", legacy: "villa-detail_hcm_7.html", name: "Villa Cadina 2", spec: "침실 5개 · 욕실 4개", image: "villa-cadina-2.webp" },
  { slug: "villa-cadina-3", legacy: "villa-detail_hcm_8.html", name: "Villa Cadina 3", spec: "침실 5개 · 욕실 6개", image: "villa-cadina-3.webp" },
  { slug: "villa-cadina-9", legacy: "villa-detail_hcm_9.html", name: "Villa Cadina 9", spec: "침실 7개 · 욕실 6개", image: "villa-cadina-9.webp" },
  { slug: "villa-yolo-b", legacy: "villa-detail_hcm_10.html", name: "Villa YOLO B", spec: "침실 5개 · 욕실 6개", image: "villa-yolo-b.webp" },
  { slug: "villa-yolo-c", legacy: "villa-detail_hcm_11.html", name: "Villa YOLO C", spec: "침실 5개 · 욕실 5개", image: "villa-yolo-c.webp" },
  { slug: "villa-yolo-d", legacy: "villa-detail_hcm_12.html", name: "Villa YOLO D", spec: "침실 5개 · 욕실 5개", image: "villa-yolo-d.webp" },
  { slug: "villa-yolo-e", legacy: "villa-detail_hcm_13.html", name: "Villa YOLO E", spec: "침실 4개 · 욕실 4개", image: "villa-yolo-e.webp" },
  { slug: "grass-pool-villa-5room", legacy: "villa-detail_hcm_14.html", name: "호치민 5룸 잔디 풀빌라", spec: "침실 5개", image: "villa-grass-5room.webp" },
  { slug: "mango-pool-villa-4room", legacy: "villa-detail_hcm_15.html", name: "호치민 4룸 망고 풀빌라", spec: "침실 4개", image: "villa-mango-4room.webp" },
];
